fields = [
    'usb__id', 'usb__version', 'usb__on_to_go', 'platform__gpu_chipset',
    'platform__id', 'platform__core_count', 'platform__cpu_chipset',
    'sound__id', 'sound__jack', 'sound__speaker_quality', 'storage__id',
    'storage__size', 'storage__technology', 'operating_system__id',
    'operating_system__os', 'operating_system__version', 'operating_system__interface',
    'brand__id', 'brand__name', 'brand__country', 'battery__wireless_charging',
    'battery__id', 'battery__type_select', 'battery__capacity', 'battery__removable',
    'battery__features', 'camera__id', 'camera__is_front_camera', 'camera__usage',
    'camera__pixel_count', 'camera__diaphragm', 'camera__pixel_size',
    'camera__features', 'camera__camera_model', 'sensor__id', 'sensor__fingerprint_type',
    'sensor__fingerprint', 'sensor__accelerometer', 'sensor__gyroscope',
    'sensor__proximity', 'sensor__compass', 'sensor__barometer', 'sensor__h2o',
    'sensor__beat_rate', 'sensor__temperature', 'sensor__laser', 'sensor__face_id',
    'body__id', 'body__size', 'body__weight', 'body__display_features', 'body__display',
    'body__resolution', 'body__protection', 'body__ip_certificate', 'body__always_on_display',
    'body__material__id', 'body__material__frame', 'body__material__back_glass',
    'body__material__front_glass', 'body__color__name', 'network__id', 'network__nfc',
    'network__radio', 'network__sim_slot', 'network__infrared', 'network__gps__a_gps',
    'network__gps__bds', 'network__gps__galileo', 'network__gps__glonass',
    'network__gps__dual_gps', 'network__bluetooth__version', 'network__bluetooth__a2dp',
    'network__bluetooth__le', 'network__bluetooth__aptx', 'network__bluetooth__edr',
    'network__cell_network__c_2g_bands', 'network__cell_network__c_3g_bands',
    'network__cell_network__c_4g_bands', 'network__cell_network__c_5g_bands', 'name',
    'description', 'date', 'model', 'price', 'back_camera_features', 'front_camera_features',
    'image_stabilization', 'back_camera_video_quality', 'front_camera_video_quality',
    'pros', 'cons', 'ram__number'
]