# Generated by Django 4.0.3 on 2022-03-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
                ('usb', models.CharField(max_length=255)),
                ('cons', models.TextField()),
                ('pros', models.TextField()),
                ('description', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneImgUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to='phone.phone')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.ManyToManyField(related_name='phone', to='phone.ram'),
        ),
    ]
