# Generated by Django 4.0.3 on 2022-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='model',
        ),
        migrations.AddField(
            model_name='phone',
            name='pattern',
            field=models.CharField(blank=True, default='A', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_models',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
    ]
