# Generated by Django 4.0.3 on 2022-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_rename_video_quality_phone_back_camera_video_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='sim_slot',
            field=models.CharField(max_length=128),
        ),
    ]
