# Generated by Django 4.0.3 on 2022-03-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_body_color_network_alter_ram_number_wifi_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='usb',
        ),
        migrations.AlterField(
            model_name='phone',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ram',
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone', to='phone.ram'),
        ),
        migrations.CreateModel(
            name='Usb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('on_to_go', models.BooleanField(default=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usb', to='phone.phone')),
            ],
        ),
    ]
