# Generated by Django 4.0.3 on 2022-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_phone_phone_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='pattern',
            field=models.CharField(blank=True, default='A', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_models',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
