# Generated by Django 4.0.3 on 2022-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_remove_phone_usb_alter_phone_date_remove_phone_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellnetwork',
            name='c_2g_bands',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cellnetwork',
            name='c_3g_bands',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cellnetwork',
            name='c_4g_bands',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cellnetwork',
            name='c_5g_bands',
            field=models.TextField(null=True),
        ),
    ]
