# Generated by Django 4.0.3 on 2022-03-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_phone_pattern_alter_phone_phone_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='gnss',
            field=models.BooleanField(default=False),
        ),
    ]
