# Generated by Django 4.0.3 on 2022-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_brand_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=models.ManyToManyField(related_name='brand', to='phone.phone'),
        ),
    ]
