# Generated by Django 4.0.3 on 2022-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_cellnetwork_c_2g_bands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='a_gps',
            field=models.BooleanField(default=False),
        ),
    ]
