# Generated by Django 4.0.3 on 2022-03-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_brand_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='core_count',
            field=models.TextField(),
        ),
    ]
