# Generated by Django 4.0.3 on 2022-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_gps_a_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='qzss',
            field=models.BooleanField(default=False),
        ),
    ]
