# Generated by Django 4.0.3 on 2022-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_alter_platform_core_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='cpu_chipset',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='gpu_chipset',
            field=models.TextField(),
        ),
    ]
