# Generated by Django 4.0.3 on 2022-03-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_alter_usb_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='pattern',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_models',
        ),
    ]
