# Generated by Django 4.0.3 on 2022-03-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_gps_qzss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='back_glass',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='phone.body'),
        ),
        migrations.AlterField(
            model_name='material',
            name='frame',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='front_glass',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
