# Generated by Django 4.0.3 on 2022-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_alter_platform_cpu_chipset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='processor_size',
            field=models.TextField(default='7nm'),
        ),
    ]
