# Generated by Django 4.0.3 on 2022-03-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_alter_platform_processor_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='processor_size',
        ),
    ]
