# Generated by Django 4.0.3 on 2022-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_alter_material_back_glass_alter_material_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='image_stabilization',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='laser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='pixel_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='pixel_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video_quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
