# Generated by Django 4.0.3 on 2022-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_camera_num_of_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='camera_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
