# Generated by Django 4.0.3 on 2022-03-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_phone_camera_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='diaphragm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
