# Generated by Django 4.0.3 on 2022-03-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_rename_camera_features_phone_back_camera_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='phone',
        ),
        migrations.AddField(
            model_name='network',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network', to='phone.phone'),
        ),
    ]
