# Generated by Django 4.0.3 on 2022-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_remove_network_phone_network_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='usage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
