# Generated by Django 4.0.3 on 2022-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_camera_diaphragm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='laser',
        ),
        migrations.AddField(
            model_name='sensor',
            name='laser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
