# Generated by Django 4.0.3 on 2022-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0013_remove_camera_laser_sensor_laser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='video_quality',
        ),
        migrations.AddField(
            model_name='phone',
            name='video_quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
