# Generated by Django 4.0.3 on 2022-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0013_camera_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
