# Generated by Django 4.0.3 on 2022-03-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0014_alter_camera_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='phone',
        ),
        migrations.AddField(
            model_name='body',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='body', to='phone.phone'),
        ),
    ]
