# Generated by Django 4.0.3 on 2022-03-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0015_remove_body_phone_body_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_front_camera',
            field=models.BooleanField(default=False),
        ),
    ]
