# Generated by Django 4.0.3 on 2022-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0015_remove_camera_phone_camera_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='image_stabilization',
        ),
        migrations.AddField(
            model_name='phone',
            name='image_stabilization',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
