# Generated by Django 4.0.3 on 2022-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0016_phone_is_front_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='is_front_camera',
        ),
        migrations.AddField(
            model_name='camera',
            name='is_front_camera',
            field=models.BooleanField(default=False),
        ),
    ]
