# Generated by Django 4.0.3 on 2022-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0017_remove_phone_is_front_camera_camera_is_front_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='interface',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
