# Generated by Django 4.0.3 on 2022-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0017_platform_processor_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='fingerprint_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
