# Generated by Django 4.0.3 on 2022-03-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0018_operatingsystem_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneimgurl',
            name='phone',
        ),
        migrations.AddField(
            model_name='phoneimgurl',
            name='phone',
            field=models.ManyToManyField(related_name='image_url', to='phone.phone'),
        ),
    ]
