# Generated by Django 4.0.3 on 2022-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0019_remove_storage_size_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifi',
            name='dual_band',
            field=models.BooleanField(default=False),
        ),
    ]
