# Generated by Django 4.0.3 on 2022-03-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0019_remove_phoneimgurl_phone_phoneimgurl_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='wireless_charging',
            field=models.BooleanField(choices=[('Yes', 'Supprot Wireless Charging'), ('No', 'not Supprot Wireless Charging'), ('Unknowkn', 'not Specified')], default='No', max_length=32),
        ),
    ]
