# Generated by Django 4.0.3 on 2022-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0020_wifi_dual_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='phone',
        ),
        migrations.AddField(
            model_name='battery',
            name='phone',
            field=models.ManyToManyField(related_name='battery', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='bluetooth',
            name='network',
        ),
        migrations.AddField(
            model_name='bluetooth',
            name='network',
            field=models.ManyToManyField(related_name='bluetooth', to='phone.network'),
        ),
        migrations.RemoveField(
            model_name='body',
            name='phone',
        ),
        migrations.AddField(
            model_name='body',
            name='phone',
            field=models.ManyToManyField(related_name='body', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='phone',
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.ManyToManyField(related_name='brand', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='cellnetwork',
            name='network',
        ),
        migrations.AddField(
            model_name='cellnetwork',
            name='network',
            field=models.ManyToManyField(related_name='cell_network', to='phone.network'),
        ),
        migrations.RemoveField(
            model_name='gps',
            name='network',
        ),
        migrations.AddField(
            model_name='gps',
            name='network',
            field=models.ManyToManyField(related_name='gps', to='phone.network'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='body',
        ),
        migrations.AddField(
            model_name='material',
            name='body',
            field=models.ManyToManyField(blank=True, null=True, related_name='material', to='phone.body'),
        ),
        migrations.RemoveField(
            model_name='network',
            name='phone',
        ),
        migrations.AddField(
            model_name='network',
            name='phone',
            field=models.ManyToManyField(related_name='network', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='operatingsystem',
            name='phone',
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='phone',
            field=models.ManyToManyField(related_name='operating_system', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='platform',
            name='phone',
        ),
        migrations.AddField(
            model_name='platform',
            name='phone',
            field=models.ManyToManyField(related_name='platform', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='phone',
        ),
        migrations.AddField(
            model_name='sensor',
            name='phone',
            field=models.ManyToManyField(related_name='sensor', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='sound',
            name='phone',
        ),
        migrations.AddField(
            model_name='sound',
            name='phone',
            field=models.ManyToManyField(related_name='sound', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='storage',
            name='phone',
        ),
        migrations.AddField(
            model_name='storage',
            name='phone',
            field=models.ManyToManyField(related_name='storage', to='phone.phone'),
        ),
        migrations.RemoveField(
            model_name='wifi',
            name='network',
        ),
        migrations.AddField(
            model_name='wifi',
            name='network',
            field=models.ManyToManyField(related_name='wifi', to='phone.network'),
        ),
    ]
