# Generated by Django 4.0.3 on 2022-03-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0020_alter_battery_wireless_charging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='wireless_charging',
            field=models.CharField(choices=[('Yes', 'Supprot Wireless Charging'), ('No', 'not Supprot Wireless Charging'), ('Unknown', 'not Specified')], default='No', max_length=32),
        ),
    ]
