# Generated by Django 4.0.3 on 2022-03-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0021_remove_battery_phone_battery_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='num_of_camera',
        ),
    ]
