# Generated by Django 4.0.3 on 2022-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0022_remove_camera_num_of_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='diaphragm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.RemoveField(
            model_name='usb',
            name='phone',
        ),
        migrations.AddField(
            model_name='usb',
            name='phone',
            field=models.ManyToManyField(related_name='usb', to='phone.phone'),
        ),
    ]
