# Generated by Django 4.0.3 on 2022-03-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0022_alter_network_infrared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='nfc',
            field=models.CharField(choices=[('Yes', 'Have NFC'), ('No', 'Have not NFC'), ('Unknown', 'not Specified')], default='Yes', max_length=32),
        ),
    ]
