# Generated by Django 4.0.3 on 2022-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0026_alter_body_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='face_id',
            field=models.BooleanField(default=False),
        ),
    ]
