# Generated by Django 4.0.3 on 2022-03-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0027_sensor_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='speaker_quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
